---
- name: Desplegar aplicación Flask con Nginx
  hosts: webserver
  become: true
  vars:
    flask_port: 5000  # Variable para el puerto de Flask

  tasks:
    - name: Instalar Nginx
      apt:
        name: nginx
        state: present
        update_cache: yes

    - name: Instalar Python y dependencias
      apt:
        name:
          - python3
          - python3-pip
        state: present

    - name: Instalar Flask
      pip:
        name: flask

    - name: Copiar configuración de Nginx
      copy:
        src: files/nginx.conf
        dest: /etc/nginx/sites-available/flask
        owner: root
        group: root
        mode: '0644'

    - name: Activar configuración de Nginx
      file:
        src: /etc/nginx/sites-available/flask
        dest: /etc/nginx/sites-enabled/flask
        state: link

    - name: Eliminar la configuración por defecto de Nginx
      file:
        path: /etc/nginx/sites-enabled/default
        state: absent

    - name: Reiniciar Nginx
      service:
        name: nginx
        state: restarted
        enabled: yes

    - name: Copiar aplicación Flask
      copy:
        src: files/app.py
        dest: /opt/app.py
        owner: root
        group: root
        mode: '0755'

    - name: Crear servicio systemd para la aplicación Flask
      copy:
        dest: /etc/systemd/system/flask-app.service
        content: |
          [Unit]
          Description=Flask Application
          After=network.target

          [Service]
          ExecStart=/usr/bin/python3 /opt/app.py
          Restart=always
          User=root

          [Install]
          WantedBy=multi-user.target
        owner: root
        group: root
        mode: '0644'

    - name: Recargar systemd y habilitar servicio Flask
      shell: |
        systemctl daemon-reload
        systemctl enable flask-app
        systemctl start flask-app
